---
plugin: aws_ec2
aws_access_key: AKIAV45FVEXOE7RMBHW4
aws_secret_key: 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

regions:
  - eu-west-3

keyed_groups:
  - key: tags
    prefix: tag
  - prefix: instance_type
    key: instance_type
  - key: placement.region
    prefix: aws_region
