version: "3"
services:
  postgres:
    image: "postgres:12"
    container_name: "postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=student
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data

  backend:
    #build: .
    image: kraskobohdan/demo:36
    container_name: "backend"
    ports:
      - "8080:8080"
    depends_on:
      - postgres

