---
- name: Ansible Test Playbook
  gather_facts: false
  hosts: aws_region_eu_west_3
  tasks:
    - name: install python-pip
      yum:
        name: python-pip
        state: present
      become: true
    - name: Install boto3 and botocore with pip3 module
      pip:
        name: 
        - boto3
      become: true
