server:
  port: 8888
  error:
    include-message: always
    include-binding-errors: always

app:
  datasource:
    jdbc-url: jdbc:postgresql://postgres:5432/student
    username: postgres
    password: password
    pool-size: 30
